export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const ADD_LIST = "ADD_LIST";
export const IMPORT_LIST = "IMPORT_LIST";
export const TOGGLE_SIDE = "TOGGLE_SIDE";
export const SELECT_DASHBOARD = "SELECT_DASHBOARD";
export const CREATE_DASHBOARD = "CREATE_DASHBOARD";
export const CREATE_DASHBOARD_SUCCESS = "CREATE_DASHBOARD_SUCCESS";
export const CREATE_DASHBOARD_ERROR = "CREATE_DASHBOARD_ERROR";
export const IMPORT_DASHBOARDS = "IMOPRT_DASHBOARDS";
export const UPDATE_DASHBOARD_SUCCESS = "IMOPRT_DASHBOARD";
export const UPDATE_DASHBOARD_ERROR = "IMOPRT_DASHBOARD";
export const LOAD_DASHBOARD_SUCCESS = "LOAD_DASHBOARD_SUCCESS";
export const LOAD_DASHBOARD_ERROR = "LOAD_DASHBOARD_ERROR";
export const LOAD_DASHBOARDS_SUCCESS = "LOAD_DASHBOARDS_SUCCESS";
export const LOAD_DASHBOARDS_ERROR = "LOAD_DASHBOARDS_ERROR";
export const NET_ERROR = "NET_ERROR";
export const LOAD_USER = "LOAD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const PROFILE_MANAGEMENT_OPEN = "PROFILE_MANAGEMENT_OPEN";
export const PROFILE_MANAGEMENT_CLOSE = "PROFILE_MANAGEMENT_CLOSE";
export const DASHBOARD_CREATOR_CLOSE = "DASHBOARD_CREATOR_CLOSE";
export const DASHBOARD_CREATOR_OPEN = "DASHBOARD_CREATOR_OPEN";
export const DASHBOARD_CONFIG_CLOSE = "DASHBOARD_CONFIG_CLOSE";
export const DASHBOARD_CONFIG_OPEN = "DASHBOARD_CONFIG_OPEN";
export const DASHBOARD_CREATOR_ADD_LIST = "DASHBOARD_CREATOR_ADD_LIST";
export const DASHBOARD_CREATOR_REMOVE_LIST = "DASHBOARD_CREATOR_REMOVE_LIST";
export const DASHBOARD_ADD_LIST = "DASHBOARD_ADD_LIST";
export const DASHBOARD_REMOVE_LIST = "DASHBOARD_REMOVE_LIST";
export const APPROVE_ACCOUNT = "APPROVE_ACCOUNT";
export const APPROVE_ACCOUNT_END = "APPROVE_ACCOUNT_END";
export const APPROVE_ACCOUNT_SUCCESS = "APPROVE_ACCOUNT_SUCCESS";
export const APPROVE_ACCOUNT_ERROR = "APPROVE_ACCOUNT_ERROR";
export const APPROVE_ACTION_RESET = "APPROVE_ACTION_RESET";
export const CREATE_IMPORTED_DASHBOARD_SUCCESS =
  "CREATE_IMPORTED_DASHBOARD_SUCCESS";
export const CREATE_IMPORTED_DASHBOARD_ERROR =
  "CREATE_IMPORTED_DASHBOARD_ERROR";
export const DELETE_IMPORTED_DASHBOARD_ERROR =
  "DELETE_IMPORTED_DASHBOARD_ERROR";
export const DELETE_IMPORTED_DASHBOARD_SUCCESS =
  "DELETE_IMPORTED_DASHBOARD_SUCCESS";
export const UPDATE_IMPORTED_DASHBOARD_ERROR =
  "UPDATE_IMPORTED_DASHBOARD_ERROR";
export const UPDATE_IMPORTED_DASHBOARD_SUCCESS =
  "UPDATE_IMPORTED_DASHBOARD_SUCCESS";
export const LOAD_CARDS = "LOAD_CARDS";
export const LOAD_CARDS_SUCCESS = "LOAD_CARDS_SUCCESS";
export const LOAD_CARDS_ERROR = "LOAD_CARDS_ERROR";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const UPDATE_CARD_ERROR = "UPDATE_CARD_ERROR";
